version: "3"
services:
  db:
    hostname: 127.0.0.1
    image: ankane/pgvector
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=chat
      - POSTGRES_PASSWORD=chatchat
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql