spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8092

cors:
  allowed-origin: http://localhost:3000

message:
  service:
    max-message-count: 10
    min-message-count: 5
    summary-word-count: 50
