server:
  port: 8092

spring:
  profiles:
#    active: h2
    active: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

message:
  service:
    max-message-count: 10
    min-message-count: 5
    summary-word-count: 50
